### PR TITLE
Travis setup

### PR DESCRIPTION
**Pull request by rspieldenner**

### CODE REVIEW

**Comment by rspieldenner** [comment]
Figuring out the key encryption still

**Comment by rspieldenner** [comment]
TravisCI build is going to fail until this is committed.

**Comment by rspieldenner** [comment]
@adriancole I think this is ready to play with, if it works we should copy these 2 files to the other branches you release off of and then I can do the same for the other projects you're in charge of releasing.

**Comment by adriancole** [comment]
@rspieldenner cool. can I cherry-pick this onto the other branches, or should I actually copy the files?

**Comment by adriancole** [comment]
also.. is this the same thing for denominator or would the contents differ?

**Comment by rspieldenner** [comment]
cherry-pick would be fine. I'd like to see a release (or a candidate release) on a branch before we copy everywhere to make sure I got it right. If de

Denominator the contents would be almost identical. The secure bits need generated per repo I think.

**Pull request merged**
