### PR TITLE
Adds JMH benchmark module

### PR DESCRIPTION
**Pull request by adriancole**
Starts with Contract tests as this was suggested a place we may need
caching.

See #214

### CODE REVIEW

**Comment by adriancole** [comment]
@chadjaros @spencergibb If you think this will be helpful, plus one it. We can iterate on this to tune the benchmarks (warmups, what we are measuring, etc) and isolate hot spots that may need work. FWIW, here's the results on my laptop.

```
$ mvn -Dfeign.version=8.1.0
--snip--
$ target/benchmark 
# JMH 1.8 (released 1 days ago)
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java
--snip--
Benchmark                       Mode  Cnt      Score      Error  Units
ContractBenchmarks.parseFeign  thrpt   15  12485.953 ± 681.300  ops/s
ContractBenchmarks.parseJAXRS  thrpt   15  11913.406 ± 679.382  ops/s
```

**Comment by adriancole** [comment]
@jdamick I recall you had an alternate Contract idea.. this may be relevant to you, too.

**Comment by spencergibb** [comment]
:+1: I'd be interested to run this against my Spring MVC Contract.

**Comment by chadjaros** [comment]
:+1:  This is exactly what you'd need to compare performance on various caching strategies within a contract

**Pull request merged**
