### PR TITLE
Support for Apache HttpClient as Feign client

### PR DESCRIPTION
**Pull request by tburch**
I added support for using an Apache [HttpClient](https://hc.apache.org/httpcomponents-client-ga/) as the client for executing Feign HTTP requests

### CODE REVIEW

**Comment by adriancole** [comment]
Thanks, Tristan! Only a couple small things then good to go.

* Make the class final and change access to thinga marked protected to
package private. We don't want to support things that break due to
unexpected extension.
* version is 8.3 as 8.2 just went out :)

Good job and looking forward to the new driver!

**Comment by tburch** [comment]
@adriancole Any ideas as to the timing of the 8.3.x release? Or will you be publishing snapshots (looks like the last published snapshot was 7.0.0-SNAPSHOT)?

**Comment by adriancole** [comment]
I'll publish 8.3 by wednesday night pacific time.

**Comment by tburch** [comment]
@adriancole awesome!

**Comment by adriancole** [comment]
ok tag pushed. magic should make this hit maven central later this afternoon!

**Comment by tburch** [comment]
Sweet! thanks

**Pull request merged**
