### PR TITLE
read class-level @Produces/@Consumes

### PR DESCRIPTION
**Pull request by pnepywoda**
The spec says these annotations can be on the class or method levels:
https://jersey.java.net/documentation/latest/jaxrs-resources.html#d0e2065
https://jersey.java.net/documentation/latest/jaxrs-resources.html#d0e2144

### CODE REVIEW

**Comment by adriancole** [comment]
you sneakily opened a github account and published a pull request I've no changes to recommend on. great work and thanks!

**Comment by uschi2000** [comment]
Adrian, do you know when you'll publish 8.10 with support for method-level annotations?
Cheers! And thanks @pnepywoda .

**Comment by adriancole** [comment]
There's another PR in progress once that's in, sure. Latest Monday

**Comment by adriancole** [comment]
in 8.10.0!

**Comment by uschi2000** [comment]
Sweet, thanks Adrian!
  R.

**Pull request merged**
