### PR TITLE
Adds support for encoded query parameters in @QueryMap

### PR DESCRIPTION
**Pull request by edio**
Added support for encoded query parameters in QueryMap.

### CODE REVIEW

**Comment by edio** [comment]
Updated as discussed on netflix/feign channel: we do not cover edge cases that are very unlikely in real-world applications.

**Comment by adriancole** [comment]
looks good. update CHANGES and cleanup the PR description, if you don't mind (notably showing what you do now)

**Comment by edio** [comment]
Sorry for numerous edits and amendments, got a little confused. I believe I'm done now.

**Comment by adriancole** [comment]
Good work @edio

**Pull request merged**
