### PR TITLE
Add Jackson JAXB Encoder & Decoder 8.x

### PR DESCRIPTION
**Pull request by didvae**
In my company we are using JAXB to encode/decode JSON with com.fasterxml.jackson.jaxrs.json.JacksonJaxbJsonProvider

I found interesting to add this to feign.

### CODE REVIEW

**Comment by adriancole** [comment]
Looks pretty complete! What are you using feign for (if you don't mind my asking).

Mind updating the CHANGES file and removing the "created by" javadocs? Also, this needs to become a single commit (usually via git rebase and squash).

If you need help, I can do this when bringing the change in.

**Comment by didvae** [comment]
Hi Adrian, thanks for your comment!
You can drop javadoc lines, sometimes IDE's helps too much ....
We are creating a microservices infrastucture and we found feign very interesting for creating clients (we were using apache cxf).
If you can help me with the commit I'll apreciate it. I don't have so much experience with git.

**Comment by adriancole** [comment]
sorry lost track a sec.. merging this now.

**Comment by adriancole** [comment]
closed via 6b90c7c

**Pull request closed without merging**
