### PR TITLE
Move to 2.2.8 which has the release.travisci flag

### PR DESCRIPTION
**Pull request by rspieldenner**
which disables certain checks on tag releases. Another attempt at getting travis release working.

### CODE REVIEW

**Comment by adriancole** [comment]
v2.2.8 isn't yet found..

**Comment by rspieldenner** [comment]
Hadn't synced yet with the gradle plugin repo. Should be good now.

**Comment by adriancole** [comment]
picked into 7.x and 8.x

trying the tag thing again.

**Comment by adriancole** [comment]
fingers crossed https://travis-ci.org/Netflix/feign/builds/54171837

**Comment by rspieldenner** [comment]
nope 2.2.9 shortly

**Comment by adriancole** [comment]
thanks for the tenacity! this is going to be well worth the effort.

**Pull request merged**
