### PR TITLE
Demonstrates impact of advice to cache Feign.newInstance

### PR DESCRIPTION
**Pull request by adriancole**
Shows relative performance of caching various points of construction of
a Feign Api. Adds a mesobenchmark of actually performing http requests,
so that caching performance can be placed in context.

Here are the results from my macbook using an untuned latest JRE 1.8
```
Benchmark                                                       Mode  Cnt       Score       Error  Units
RealRequestBenchmarks.query_baseCaseUsingOkHttp                thrpt   15   10515.978 ±  2333.535  ops/s
RealRequestBenchmarks.query_feignUsingOkHttp                   thrpt   15    9645.363 ±  1703.632  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake                 thrpt   15   15236.726 ±  1590.752  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedApi       thrpt   15  538699.642 ± 61973.763  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedContract  thrpt   15  123527.076 ± 12364.511  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedFeign     thrpt   15   16014.656 ±  1098.113  ops/s
WhatShouldWeCacheBenchmarks.parseFeignContract                 thrpt   15   19456.233 ±  2173.663  ops/s
```

Here are the results from my macbook using an untuned latest JRE 1.7
```
Benchmark                                                       Mode  Cnt       Score       Error  Units
RealRequestBenchmarks.query_baseCaseUsingOkHttp                thrpt   15    9927.758 ±  2689.811  ops/s
RealRequestBenchmarks.query_feignUsingOkHttp                   thrpt   15    8125.193 ±  3588.980  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake                 thrpt   15    9932.296 ±   352.194  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedApi       thrpt   15  439339.629 ± 15300.471  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedContract  thrpt   15  105696.328 ±  3459.255  ops/s
WhatShouldWeCacheBenchmarks.buildAndQuery_fake_cachedFeign     thrpt   15   10062.098 ±   307.206  ops/s
WhatShouldWeCacheBenchmarks.parseFeignContract                 thrpt   15   11061.333 ±   509.096  ops/s
```

See #214

### CODE REVIEW

**Comment by adriancole** [comment]
cc @chadjaros @spencergibb @jdamick lemme know if this pulls its weight or not.

**Comment by spencergibb** [comment]
:+1:

**Comment by chadjaros** [comment]
:+1: One could assume that parsing the Feign contract would take longer for a larger contract?

**Comment by adriancole** [comment]
@chadjaros once I merge, feel free to make a benchmark for variable length contracts!

**Pull request merged**
