### PR TITLE
Fix 404 issue for Github sample

### PR DESCRIPTION
**Pull request by htynkn**
The old link is invalid, got an 404 page not found error.

### CODE REVIEW

**Comment by adriancole** [comment]
actually, the link is referencing retrofit, which did rename their sample https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/SimpleService.java

**Comment by htynkn** [comment]
thanks @adriancole

**Comment by adriancole** [comment]
Thanks for the fix! Mind squashing these commits into one?

```
git rebase -i master
# change pick to s (for squash), fix the commit message and save
git push -f origin patch-1
```

**Comment by htynkn** [comment]
Done.
Thanks for share git commands.

**Comment by adriancole** [comment]
NP cheers!

**Pull request merged**
